language: java
deploy:
  provider: heroku
  api_key:
    secure: i6BkDWc7A4AYlgK92Ss2QJ59W/JhZsZZrm/un5oq/AwZiIFsBrWbh2VQLqh1bBqi7yJ19zgdr3prk+m/BmeSkaYGch3usb1nMeREUutFE2ik6r8/wBjBAyumU47e6qiUDkc+tqD6x2QsAou5BrQFeWOyTJVALra7inYHj9RV5q9ETkwvnGtWk7OTf29h/+IxYH6iMqGY+anxHOBYfmsVfFZ/fM/utdf2gjxctJxwOA/LUmuyq8BsnFjBIUXKuK9qjO8OsDIfVd/rUQM8ioZhE+7SDu+MCZ5y8UTuNh5X/pZNFn45zN29ROnP3tffKnLxOmrcVpvfu4EvC5R9iF6v2vQc2j9L3GEponywyF4raRygK2PMmPi/gS+L6C6Kp9v0yqR0/bIYtSUhxWTmx3PjyuuhJ27fkvRDdyAX7c+VrnvQ4XktCb/tSAxL6/UzNK4GgmKyHkLeg5Z/KELujNMKBomMy1aHboCg0I79Q22B7rX2ggjdDDwB62xIt7ttvf6dfO+OOpmdONTdh9H+zRZ4BUskJCvzGChYD58hnxyOGLsUYSvnnHlhELlk2GoK9MIadugMbOHJQmyhBRi0lLoooNHroyN+IMN3FiDQ3iOv5jvrjYC5zArcRt8VlwlBvr2stuKwQTBxd+MNZK3s2rBekxjtAE1ADxugw6KBpEHU9FM=
  app: mighty-brushlands-46890
  on:
    repo: titanicfloatnone/ticTac
after_success:
  ./gradlew jacocoTestReport coveralls